//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoreItem
    {
        public int ItemId { get; set; }
        public string ItemNumber { get; set; }
        public string VendorCode { get; set; }
        public string ItemDescription { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> DeliveryCharge { get; set; }
        public Nullable<decimal> CostPrice { get; set; }
        public string Grade { get; set; }
        public Nullable<int> SubjectId { get; set; }
        public Nullable<int> ProgramId { get; set; }
        public Nullable<int> SubjectAreaId { get; set; }
        public Nullable<int> ItemTypeId { get; set; }
        public string ImageUrl { get; set; }
        public string WhatToOrder { get; set; }
        public string ECatalogNumber { get; set; }
        public string ManufacturerItemNumber { get; set; }
        public string Information { get; set; }
        public Nullable<int> ImTypeId { get; set; }
        public string Isbn13 { get; set; }
        public string Author { get; set; }
        public string Contract { get; set; }
        public string BookLanguage { get; set; }
        public string EditionNo { get; set; }
        public string KitQuantity { get; set; }
        public string Unit { get; set; }
        public string CopyrightYear { get; set; }
        public Nullable<bool> NystlIndicator { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<bool> Delete { get; set; }
        public string ParentItemNumber { get; set; }
        public Nullable<int> SortOrder { get; set; }
        public Nullable<bool> FreeWithOrder { get; set; }
        public Nullable<System.DateTime> BackOrderDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
